apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: strasserpablo@bluewin.ch
      hash: $2b$10$7ibwzSItL2qXtMF0EiFO3.ckEuWsxDUOgg0WSNiCuKfi6oEcUytdS
      # https://github.com/dexidp/dex/pull/1601/commits
      # FIXME: Use hashFromEnv instead
      username: pablo
      userID: "15841185641784"
    - email: abbcompressionheg@gmail.com
      hash: $2y$12$q5noljDFL3N8B5MMs1qN9uZ.JrNBRpoyWGthzfNhL445Oiugz2zJ
      # https://github.com/dexidp/dex/pull/1601/commits
      # FIXME: Use hashFromEnv instead
      username: abbcompressionheg 
      userID: "15841185641785"
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
