apiVersion: apps/v1
kind: Deployment
metadata:
  name: abbcompression-mysql
  namespace: abbcompression
  labels:
    app: abbcompression-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abbcompression-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abbcompression-mysql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: abbcompression-mysql
          image: mysql:8
          args:
            - --datadir
            - /var/lib/mysql/datadir
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: abbcompression-mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "false"
          ports:
            - name: dbapi
              containerPort: 3306
          readinessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"
            periodSeconds: 2
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            periodSeconds: 2
            failureThreshold: 10
          startupProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            periodSeconds: 15
            failureThreshold: 60
          volumeMounts:
            - name: pablo-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: pablo-mysql
          persistentVolumeClaim:
            claimName: pablo-mysql
