apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abbcompression-mysql
  namespace: abbcompressionheg
spec:
  storageClassName: gluster-heketi-distributed 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
