apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abbcompression-mysql
  namespace: abbcompressionheg
  StorageClass: gluster-heketi-distributed 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
