apiVersion: v1
kind: Service
metadata:
  name: abbcompression-mysql
  namespace: abbcompressionheg
  labels:
    app: abbcompression-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: dbapi
  selector:
    app: abbcompression-mysql
