apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/mpi-operator/manifests/overlays/kubeflow?ref=db6930dcd509b1d97a47bcccd1bcb1da5eaea712
images:
- name: mpioperator/mpi-operator
  newName: mpioperator/mpi-operator
  newTag: latest
  # digest: sha256:547b161ee16991a49aca90cd2b1048a2d3dbc4af42f4b9d5947a4b76c618dad4
