kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ingress-istio
  namespace: istio-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - kubeflow.strasser-kub.ch
      secretName: kubeflow-ingress-cert
  rules:
    - host: kubeflow.strasser-kub.ch
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: istio-ingressgateway
              servicePort: 443
