kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ingress-istio
  namespace: istio-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - kubeflow.strasser-kub.ch
      secretName: kubeflow-ingress-cert
  ingressClassName: istio
  rules:
    - host: kubeflow.strasser-kub.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: istio-ingressgateway 
              servicePort: 443
