kind: Service
apiVersion: v1
metadata:
  name: istio-ingressgateway-service2
  namespace: default
spec:
  ports:
    - name: p1 
      protocol: TCP
      port: 15021
      targetPort: 15021
    - name: p2
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: nginx
  type: ClusterIP
