kind: Service
apiVersion: v1
metadata:
  name: istio-ingressgateway-service
  namespace: istio-system
spec:
  ports:
    - name: status-port
      protocol: TCP
      port: 15021
      targetPort: 15021
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app: nginx
  type: ClusterIP
  sessionAffinity: None
