kind: Service
apiVersion: v1
metadata:
  name: istio-ingressgateway-service2
  namespace: default
spec:
  ports:
    - name: p2
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
