kind: Service
apiVersion: v1
metadata:
  name: istio-ingressgateway-service2
  namespace: istio-system
spec:
  ports:
    - protocol: TCP
      port: 15021
      targetPort: 15021
    - protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app: nginx
  type: ClusterIP
