apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "/asEW+fyyWMR7CZZAOUWrrnuuBRFD1vIi64f/yqFkLkuFD2LjvwDLQcYcdyXNyeO\ng+dNo/SwnuIoyC1YkLgyoqNeVJ6wcKjZfurAAfG9eXT8brljBC8ePBaFU1P0TmqR\nX609pNXu++MRwIKleyVPMQk+QiSlcQNLumHJa1hMBBM="
